package Exceptionex1;

public class ArithmaticEx1 {

	public static void main(String[] args) {
		
		try {
			int f=12/0;
		}
		catch(Exception e) {
			System.out.println(e);
			
		}

		
	}

}
